# ANN with weight initialisation and Hyperparameter tuning

In [1]:
#importing the libraries

import pandas as pd
import numpy as np

In [2]:
# Reading dataset

df=pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
# Splitting the dataset

X=df.iloc[:,3:13]
y=df.iloc[:,-1]

In [4]:
# Creating dummy variable
geography=pd.get_dummies(X['Geography'],drop_first=True)
Gender=pd.get_dummies(X['Gender'],drop_first=True)

In [5]:
X.drop(columns=['Gender','Geography'],inplace=True)

In [6]:
X=pd.concat([X,geography,Gender],axis=1)

In [7]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [8]:
# Train test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
X_train.shape,X_test.shape

((8000, 11), (2000, 11))

In [11]:
# importing keras libraries and packages

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, LeakyReLU, PReLU, ELU

In [44]:
# initialing the ANN

classifier=Sequential()

# Creating input layer
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu', input_dim=11))

# Creating Hiddenlayer
classifier.add(Dense(units=6,kernel_initializer='he_uniform', activation='relu'))

#Creating Outputlayer
classifier.add(Dense(units=1, kernel_initializer='glorot_uniform', activation='sigmoid'))

# Compiler
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting the model
model_history=classifier.fit(X_train,y_train, validation_split=0.33, batch_size=10, epochs=100)

Epoch 1/100
536/536 [==============================] - 5s 7ms/step - loss: 0.5050 - accuracy: 0.7901 - val_loss: 0.4657 - val_accuracy: 0.7989
Epoch 2/100
536/536 [==============================] - 5s 8ms/step - loss: 0.4484 - accuracy: 0.7992 - val_loss: 0.4405 - val_accuracy: 0.8001
Epoch 3/100
536/536 [==============================] - 4s 7ms/step - loss: 0.4259 - accuracy: 0.8048 - val_loss: 0.4265 - val_accuracy: 0.8039
Epoch 4/100
536/536 [==============================] - 3s 6ms/step - loss: 0.4098 - accuracy: 0.8108 - val_loss: 0.4153 - val_accuracy: 0.8088
Epoch 5/100
536/536 [==============================] - 4s 7ms/step - loss: 0.3974 - accuracy: 0.8169 - val_loss: 0.4056 - val_accuracy: 0.8145
Epoch 6/100
536/536 [==============================] - 4s 7ms/step - loss: 0.3883 - accuracy: 0.8231 - val_loss: 0.4006 - val_accuracy: 0.8194
Epoch 7/100
536/536 [==============================] - 4s 8ms/step - loss: 0.3810 - accuracy: 0.8326 - val_loss: 0.3934 - val_accuracy: 0.8307

Epoch 58/100
536/536 [==============================] - 7s 13ms/step - loss: 0.3295 - accuracy: 0.8634 - val_loss: 0.3564 - val_accuracy: 0.8497
Epoch 59/100
536/536 [==============================] - 5s 10ms/step - loss: 0.3300 - accuracy: 0.8615 - val_loss: 0.3568 - val_accuracy: 0.8519
Epoch 60/100
536/536 [==============================] - 7s 12ms/step - loss: 0.3296 - accuracy: 0.8636 - val_loss: 0.3567 - val_accuracy: 0.8493
Epoch 61/100
536/536 [==============================] - 5s 8ms/step - loss: 0.3294 - accuracy: 0.8623 - val_loss: 0.3567 - val_accuracy: 0.8489
Epoch 62/100
536/536 [==============================] - 4s 7ms/step - loss: 0.3296 - accuracy: 0.8638 - val_loss: 0.3562 - val_accuracy: 0.8478
Epoch 63/100
536/536 [==============================] - 4s 7ms/step - loss: 0.3292 - accuracy: 0.8623 - val_loss: 0.3574 - val_accuracy: 0.8478
Epoch 64/100
536/536 [==============================] - 3s 5ms/step - loss: 0.3297 - accuracy: 0.8640 - val_loss: 0.3571 - val_accura

In [46]:
# prediting for test data

y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

63/63 [==============================] - 0s 5ms/step


In [48]:
# Making confusion matrix
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
cm

array([[1524,   71],
       [ 217,  188]], dtype=int64)

In [50]:
# Calculating accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.856

In [52]:
# initialing the ANN with Dropout

classifier=Sequential()

# Creating input layer
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation='relu', input_dim=11))
classifier.add(Dropout(0.2))

# Creating Hiddenlayer
classifier.add(Dense(units=6,kernel_initializer='he_uniform', activation='relu'))
classifier.add(Dropout(0.2))

# Creating Hiddenlayer
classifier.add(Dense(units=6,kernel_initializer='he_uniform', activation='relu'))
classifier.add(Dropout(0.2))

#Creating Outputlayer
classifier.add(Dense(units=1, kernel_initializer='glorot_uniform', activation='sigmoid'))

# Compiler
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fitting the model
model_history=classifier.fit(X_train,y_train, validation_split=0.33, batch_size=10, epochs=50)

Epoch 1/50
536/536 [==============================] - 7s 10ms/step - loss: 0.5772 - accuracy: 0.7705 - val_loss: 0.4859 - val_accuracy: 0.7955
Epoch 2/50
536/536 [==============================] - 5s 9ms/step - loss: 0.5131 - accuracy: 0.7916 - val_loss: 0.4754 - val_accuracy: 0.7955
Epoch 3/50
536/536 [==============================] - 3s 6ms/step - loss: 0.4929 - accuracy: 0.7946 - val_loss: 0.4648 - val_accuracy: 0.7955
Epoch 4/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4729 - accuracy: 0.7949 - val_loss: 0.4543 - val_accuracy: 0.7955
Epoch 5/50
536/536 [==============================] - 4s 7ms/step - loss: 0.4696 - accuracy: 0.7957 - val_loss: 0.4484 - val_accuracy: 0.7955
Epoch 6/50
536/536 [==============================] - 7s 12ms/step - loss: 0.4622 - accuracy: 0.7960 - val_loss: 0.4437 - val_accuracy: 0.7955
Epoch 7/50
536/536 [==============================] - 4s 7ms/step - loss: 0.4603 - accuracy: 0.7962 - val_loss: 0.4386 - val_accuracy: 0.7955
Epoc

In [53]:
# prediting for test data

y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

# Making confusion matrix
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
cm

63/63 [==============================] - 1s 8ms/step


array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [54]:
# Calculating accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.7975

### Hyper parameter tuning using GridSearchCv

In [46]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding, Flatten, LeakyReLU, BatchNormalization, Dropout
from keras.activations import relu, sigmoid

In [51]:
def create_model(layers,activation):
    model=Sequential()
    for i, nodes in enumerate(layers):
        if i==0:
            model.add(Dense(nodes,input_dim=X_train.shape[1]))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        else:
            model.add(Dense(nodes))
            model.add(Activation(activation))
            model.add(Dropout(0.3))
        
    model.add(Dense(units=1, kernel_initializer='glorot_uniform', activation='sigmoid'))
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[['accuracy']])
    return model

In [52]:
model=KerasClassifier(build_fn=create_model,verbose=0)

C:\Users\BRAG\AppData\Local\Temp\ipykernel_7484\1314563489.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  model=KerasClassifier(build_fn=create_model,verbose=0)


In [53]:
layers=[[20],[40,20],[45,30,15]]
activation=['sigmoid','relu']
param_grid=dict(layers=layers, activation= activation, batch_size=[128,256], epochs=[30])
grid=GridSearchCV(estimator=model, param_grid=param_grid,cv=5)

In [54]:
grid_result=grid.fit(X_train,y_train)

In [55]:
print(grid_result.best_params_,grid_result.best_score_)

{'activation': 'relu', 'batch_size': 128, 'epochs': 30, 'layers': [45, 30, 15]} 0.8570000052452087


In [56]:
pred_y=grid.predict(X_test)
y_pred=(pred_y>0.5)

63/63 [==============================] - 0s 1ms/step


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_pred,y_test)
cm

array([[1538,  221],
       [  57,  184]], dtype=int64)

In [59]:
score=accuracy_score(y_pred,y_test)
score

0.861

### Hyperparameter tuning with randomsearch

In [61]:
import pandas as pd
import keras
from keras import layers
from kerastuner.tuners import RandomSearch

C:\Users\BRAG\AppData\Local\Temp\ipykernel_7484\1847409054.py:4: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  from kerastuner.tuners import RandomSearch


In [63]:
def build_model(hp):
    model=keras.Sequential()
    for i in range(hp.Int('num_layers',2,20)):   # 2, 20 is range 2-20
        model.add(layers.Dense(units=hp.Int('units_'+str(i),
                                           min_value=32,
                                           max_value=512,
                                           step=32),
                              activation='relu'))
        model.add(layers.Dense(1, activation='sigmoid'))
        model.compile(
                    optimizer=keras.optimizers.Adam(
                    hp.Choice('learning_rate',[1e-2,1e-3,1e-4])),
                loss='binary_crossentropy',
                metrics=['accuracy'])
    return model

In [73]:
tuner=RandomSearch(
    build_model,
    objective='accuracy',
    max_trials=5,
    executions_per_trial=3,
    directory='projec1',
    project_name='Binary classification')

In [74]:
tuner.search_space_summary()

Search space summary
Default search space size: 4
num_layers (Int)
{'default': None, 'conditions': [], 'min_value': 2, 'max_value': 20, 'step': 1, 'sampling': None}
units_0 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}
learning_rate (Choice)
{'default': 0.01, 'conditions': [], 'values': [0.01, 0.001, 0.0001], 'ordered': True}
units_1 (Int)
{'default': None, 'conditions': [], 'min_value': 32, 'max_value': 512, 'step': 32, 'sampling': None}


In [75]:
tuner.search(X_train,y_train,epochs=50,validation_data=(X_test,y_test))

Trial 5 Complete [00h 03m 44s]
accuracy: 0.7960000038146973

Best accuracy So Far: 0.8610000014305115
Total elapsed time: 00h 12m 19s
INFO:tensorflow:Oracle triggered exit


In [76]:
tuner.results_summary()

Results summary
Results in projec1\Binary classification
Showing 10 best trials
Trial summary
Hyperparameters:
num_layers: 3
units_0: 480
learning_rate: 0.0001
units_1: 160
units_2: 288
units_3: 160
units_4: 480
units_5: 448
units_6: 448
units_7: 288
units_8: 320
units_9: 224
units_10: 128
units_11: 128
units_12: 288
units_13: 480
units_14: 96
Score: 0.8610000014305115
Trial summary
Hyperparameters:
num_layers: 15
units_0: 288
learning_rate: 0.001
units_1: 32
units_2: 32
units_3: 32
units_4: 32
units_5: 32
units_6: 32
units_7: 32
units_8: 32
units_9: 32
units_10: 32
units_11: 32
units_12: 32
units_13: 32
units_14: 32
Score: 0.7960000038146973
Trial summary
Hyperparameters:
num_layers: 8
units_0: 64
learning_rate: 0.01
units_1: 64
units_2: 288
units_3: 320
units_4: 384
units_5: 320
units_6: 256
units_7: 352
units_8: 192
units_9: 352
units_10: 480
units_11: 288
units_12: 320
units_13: 256
units_14: 64
Score: 0.7960000038146973
Trial summary
Hyperparameters:
num_layers: 11
units_0: 256
le